mlterm*: update to 3.9.5

diff --git a/x11/mlterm/files/0005-Remove-hardcoded-paths-to-usr-local.patch b/x11/mlterm/files/0005-Remove-hardcoded-paths-to-usr-local.patch
--- a/x11/mlterm/files/0005-Remove-hardcoded-paths-to-usr-local.patch
+++ b/x11/mlterm/files/0005-Remove-hardcoded-paths-to-usr-local.patch
@@ -1,62 +1,64 @@
-From ff1e559684373579aa413c780278df8244633e94 Mon Sep 17 00:00:00 2001
+From f6b60d33e756a8bfc5bc012c83c872ceb267524c Mon Sep 17 00:00:00 2001
 From: Sergey Fedorov <vital.had@gmail.com>
-Date: Sat, 2 Aug 2025 06:09:09 +0800
-Subject: [PATCH 4/4] Do not hardcode wrong paths
+Date: Mon, 13 Jul 2026 11:45:20 +0800
+Subject: [PATCH 5/6] Remove hardcoded paths to /usr/local
 
 ---
- baselib/configure                    | 2 +-
- configure                            | 2 +-
- configure.in                         | 6 +++---
- encodefilter/module/Makefile.in      | 3 +--
- encodefilter/src/Makefile.in         | 2 +-
- encodefilter/src/ef_tblfunc_loader.h | 2 +-
- inputmethod/canna/Makefile.in        | 3 +--
- inputmethod/fcitx/Makefile.in        | 3 +--
- inputmethod/ibus/Makefile.in         | 3 +--
- inputmethod/iiimf/Makefile.in        | 3 +--
- inputmethod/kbd/Makefile.in          | 3 +--
- inputmethod/m17nlib/Makefile.in      | 3 +--
- inputmethod/scim/Makefile.in         | 3 +--
- inputmethod/skk/Makefile.in          | 3 +--
- inputmethod/uim/Makefile.in          | 3 +--
- inputmethod/wnn/Makefile.in          | 3 +--
- java/Makefile.in                     | 2 +-
- libind/Makefile.in                   | 2 +-
- libvterm/Makefile.in                 | 2 +-
- main/Makefile.in                     | 6 +++---
- main/main-con.c                      | 2 +-
- script/config.rpath                  | 2 +-
- tool/accessories/Makefile            | 2 +-
- tool/mlconfig/Makefile.in            | 1 -
- tool/mlconfig/mc_im.c                | 2 +-
- tool/mlconfig/mc_sb_view.c           | 2 +-
- tool/mlfc/Makefile.in                | 4 ++--
- tool/mlimgloader/Makefile.in         | 4 ++--
- tool/mlmenu/main.c                   | 2 +-
- tool/registobmp/Makefile.in          | 4 ++--
- tool/servman/Makefile.in             | 4 ++--
- uitoolkit/Makefile.in                | 2 +-
- uitoolkit/fb/ui_virtual_kbd.c        | 2 +-
- uitoolkit/libotl/Makefile.in         | 4 ++--
- uitoolkit/libotl/otl.h               | 2 +-
- uitoolkit/libtype/Makefile.in        | 4 ++--
- uitoolkit/ui_im.c                    | 2 +-
- uitoolkit/ui_sb_view_factory.c       | 4 ++--
- uitoolkit/xlib/ui_type_loader.c      | 2 +-
- vtemu/Makefile.in                    | 2 +-
- vtemu/libctl/Makefile.in             | 2 +-
- vtemu/libctl/vt_iscii.c              | 2 +-
- vtemu/libptymosh/Makefile.in         | 2 +-
- vtemu/libptyssh/Makefile.in          | 2 +-
- vtemu/vt_ctl_loader.c                | 2 +-
- vtemu/vt_pty_mosh.c                  | 2 +-
- vtemu/vt_pty_ssh.c                   | 2 +-
- vtemu/vt_term_manager.c              | 2 +-
- vtemu/vt_transfer.c                  | 2 +-
- 49 files changed, 59 insertions(+), 71 deletions(-)
+ baselib/configure                    |  8 ++++----
+ baselib/src/bl_path.c                |  4 ++--
+ baselib/src/bl_path.h                |  2 +-
+ configure                            | 10 ++++++----
+ configure.in                         |  2 +-
+ encodefilter/configure               |  8 ++++----
+ encodefilter/module/Makefile.in      |  3 +--
+ encodefilter/src/Makefile.in         |  2 +-
+ encodefilter/src/ef_tblfunc_loader.h |  2 +-
+ inputmethod/canna/Makefile.in        |  3 +--
+ inputmethod/fcitx/Makefile.in        |  3 +--
+ inputmethod/ibus/Makefile.in         |  3 +--
+ inputmethod/iiimf/Makefile.in        |  3 +--
+ inputmethod/kbd/Makefile.in          |  3 +--
+ inputmethod/m17nlib/Makefile.in      |  3 +--
+ inputmethod/scim/Makefile.in         |  3 +--
+ inputmethod/skk/Makefile.in          |  3 +--
+ inputmethod/uim/Makefile.in          |  3 +--
+ inputmethod/wnn/Makefile.in          |  3 +--
+ libind/Makefile.in                   |  2 +-
+ libvterm/Makefile.in                 |  2 +-
+ main/Makefile.in                     |  6 +++---
+ main/main-con.c                      |  2 +-
+ script/config.rpath                  |  2 +-
+ tool/accessories/Makefile            |  2 +-
+ tool/mlconfig/Makefile.in            |  1 -
+ tool/mlconfig/mc_im.c                |  2 +-
+ tool/mlconfig/mc_sb_view.c           |  2 +-
+ tool/mlfc/Makefile.in                |  4 ++--
+ tool/mlimgloader/Makefile.in         |  5 ++---
+ tool/mlmenu/main.c                   |  2 +-
+ tool/registobmp/Makefile.in          |  4 ++--
+ tool/servman/Makefile.in             |  4 ++--
+ uitoolkit/Makefile.in                |  2 +-
+ uitoolkit/fb/ui_virtual_kbd.c        |  2 +-
+ uitoolkit/libotl/Makefile.in         |  4 ++--
+ uitoolkit/libotl/otl.h               |  2 +-
+ uitoolkit/libtype/Makefile.in        |  4 ++--
+ uitoolkit/ui_im.c                    |  2 +-
+ uitoolkit/ui_sb_view_factory.c       |  4 ++--
+ uitoolkit/xlib/ui_type_loader.c      |  2 +-
+ vtemu/Makefile.in                    |  2 +-
+ vtemu/libctl/Makefile.in             |  2 +-
+ vtemu/libctl/vt_iscii.c              |  2 +-
+ vtemu/libptymosh/Makefile.in         |  2 +-
+ vtemu/libptyssh/Makefile.in          |  2 +-
+ vtemu/vt_ctl_loader.c                |  2 +-
+ vtemu/vt_pty_mosh.c                  |  2 +-
+ vtemu/vt_pty_ssh.c                   |  2 +-
+ vtemu/vt_term_manager.c              |  2 +-
+ vtemu/vt_transfer.c                  |  2 +-
+ 51 files changed, 71 insertions(+), 82 deletions(-)
 
 diff --git baselib/configure baselib/configure
-index a928cdba..5ad83605 100755
+index 893380cc..52d0e26e 100755
 --- baselib/configure
 +++ baselib/configure
 @@ -575,7 +575,7 @@ ac_hostname=`(hostname || uname -n) 2>/dev/null | sed 1q`
@@ -68,8 +70,57 @@ index a928cdba..5ad83605 100755
  ac_clean_files=
  ac_config_libobj_dir=.
  LIBOBJS=
+@@ -10166,7 +10166,7 @@ BEGIN {RS = " "; FS = "/|\n";} {
+   esac
+   sys_lib_search_path_spec=`$ECHO "$lt_search_path_spec" | $lt_NL2SP`
+ else
+-  sys_lib_search_path_spec="/lib /usr/lib /usr/local/lib"
++  sys_lib_search_path_spec="/lib /usr/lib /opt/local/lib"
+ fi
+ library_names_spec=
+ libname_spec='lib$name'
+@@ -10450,8 +10450,8 @@ darwin* | rhapsody*)
+   shlibpath_var=DYLD_LIBRARY_PATH
+   shrext_cmds='`test .$module = .yes && echo .so || echo .dylib`'
+ 
+-  sys_lib_search_path_spec="$sys_lib_search_path_spec /usr/local/lib"
+-  sys_lib_dlsearch_path_spec='/usr/local/lib /lib /usr/lib'
++  sys_lib_search_path_spec="$sys_lib_search_path_spec /opt/local/lib"
++  sys_lib_dlsearch_path_spec='/opt/local/lib /lib /usr/lib'
+   ;;
+ 
+ dgux*)
+diff --git baselib/src/bl_path.c baselib/src/bl_path.c
+index f165b54d..478b3f5a 100644
+--- baselib/src/bl_path.c
++++ baselib/src/bl_path.c
+@@ -391,9 +391,9 @@ static void TEST_bl_path_common(void) {
+   char uri3[] = "ken@localhost.localdomain:22:utf8";
+   char uri4[] = "ken@localhost.localdomain";
+   char uri5[] = "ssh://localhost.localdomain";
+-  char uri6[] = "telnet://ken@localhost.localdomain:22:eucjp/usr/local/";
++  char uri6[] = "telnet://ken@localhost.localdomain:22:eucjp/opt/local/";
+   char uri7[] = "ssh://ken@localhost.localdomain:22:eucjp/";
+-  char uri8[] = "ssh://localhost:eucjp/usr/local";
++  char uri8[] = "ssh://localhost:eucjp/opt/local";
+   char *user;
+   char *proto;
+   char *host;
+diff --git baselib/src/bl_path.h baselib/src/bl_path.h
+index 144c629f..bba93cd5 100644
+--- baselib/src/bl_path.h
++++ baselib/src/bl_path.h
+@@ -27,7 +27,7 @@
+ #endif
+ #else
+ #ifndef LIBEXECDIR
+-#define BL_LIBEXECDIR(suffix) "/usr/local/libexec/" suffix
++#define BL_LIBEXECDIR(suffix) "/opt/local/libexec/" suffix
+ #else
+ #define BL_LIBEXECDIR(suffix) LIBEXECDIR "/" suffix
+ #endif
 diff --git configure configure
-index 649dd24c..99016291 100755
+index 8baa92bc..4b88d01a 100755
 --- configure
 +++ configure
 @@ -575,7 +575,7 @@ ac_hostname=`(hostname || uname -n) 2>/dev/null | sed 1q`
@@ -81,31 +132,81 @@ index 649dd24c..99016291 100755
  ac_clean_files=
  ac_config_libobj_dir=.
  LIBOBJS=
-diff --git configure.in configure.in
-index 171434cb..aaa609f6 100644
---- configure.in
-+++ configure.in
-@@ -1198,7 +1198,7 @@ w3mmlconfig)
+@@ -11611,8 +11611,8 @@ darwin* | rhapsody*)
+   shlibpath_var=DYLD_LIBRARY_PATH
+   shrext_cmds='`test .$module = .yes && echo .so || echo .dylib`'
+ 
+-  sys_lib_search_path_spec="$sys_lib_search_path_spec /usr/local/lib"
+-  sys_lib_dlsearch_path_spec='/usr/local/lib /lib /usr/lib'
++  sys_lib_search_path_spec="$sys_lib_search_path_spec /opt/local/lib"
++  sys_lib_dlsearch_path_spec='/opt/local/lib /lib /usr/lib'
+   ;;
+ 
+ dgux*)
+@@ -16307,6 +16307,8 @@ fi
+ # Standard set of common directories for X headers.
+ # Check X11 before X11Rn because it is often a symlink to the current release.
+ ac_x_header_dirs='
++/opt/local/include
++
+ /usr/X11/include
+ /usr/X11R7/include
+ /usr/X11R6/include
+@@ -21880,7 +21882,7 @@ fi
  		echo "** WARNING  **"
  		echo " couldn't find perl in PATH environment variable."
  		echo ""
 -		PERL="/usr/local/bin/perl" # should be "/usr/bin/env perl"?
-+		PERL="/usr/bin/perl" # should be "/usr/bin/env perl"?
++		PERL="/usr/bin/perl" # may also be "/opt/local/bin/perl"
  	fi
  	MAKE_DIRS2="tool/w3mmlconfig ${MAKE_DIRS2}"
  	OUTPUT_FILES="tool/w3mmlconfig/Makefile tool/w3mmlconfig/mlconfig.cgi tool/w3mmlconfig/w3mmlconfig ${OUTPUT_FILES}"
-@@ -1615,9 +1615,9 @@ if test "x$wnn" != "xno" ; then
- 		if test -d /usr/pkg/share/wnn ; then
- 			WNN_CFLAGS="-DWNNLIBDIR=\\\"/usr/pkg/share\\\""
- 		elif test -d /usr/local/share/wnn ; then
--			WNN_CFLAGS="-DWNNLIBDIR=\\\"/usr/local/share\\\""
-+			WNN_CFLAGS="-DWNNLIBDIR=\\\"/opt/local/share\\\""
- 		elif test -d /usr/local/lib/wnn ; then
--			WNN_CFLAGS="-DWNNLIBDIR=\\\"/usr/local/lib\\\""
-+			WNN_CFLAGS="-DWNNLIBDIR=\\\"/opt/local/lib\\\""
- 		elif test -d /usr/share/wnn ; then
- 			WNN_CFLAGS="-DWNNLIBDIR=\\\"/usr/share\\\""
- 		else
+diff --git configure.in configure.in
+index 6397bc0a..1888f767 100644
+--- configure.in
++++ configure.in
+@@ -1204,7 +1204,7 @@ w3mmlconfig)
+ 		echo "** WARNING  **"
+ 		echo " couldn't find perl in PATH environment variable."
+ 		echo ""
+-		PERL="/usr/local/bin/perl" # should be "/usr/bin/env perl"?
++		PERL="/usr/bin/perl" # may also be "/opt/local/bin/perl"
+ 	fi
+ 	MAKE_DIRS2="tool/w3mmlconfig ${MAKE_DIRS2}"
+ 	OUTPUT_FILES="tool/w3mmlconfig/Makefile tool/w3mmlconfig/mlconfig.cgi tool/w3mmlconfig/w3mmlconfig ${OUTPUT_FILES}"
+diff --git encodefilter/configure encodefilter/configure
+index 2d16a43d..13c0afb6 100755
+--- encodefilter/configure
++++ encodefilter/configure
+@@ -575,7 +575,7 @@ ac_hostname=`(hostname || uname -n) 2>/dev/null | sed 1q`
+ #
+ # Initializations.
+ #
+-ac_default_prefix=/usr/local
++ac_default_prefix=/opt/local
+ ac_clean_files=
+ ac_config_libobj_dir=.
+ LIBOBJS=
+@@ -10051,7 +10051,7 @@ BEGIN {RS = " "; FS = "/|\n";} {
+   esac
+   sys_lib_search_path_spec=`$ECHO "$lt_search_path_spec" | $lt_NL2SP`
+ else
+-  sys_lib_search_path_spec="/lib /usr/lib /usr/local/lib"
++  sys_lib_search_path_spec="/lib /usr/lib /opt/local/lib"
+ fi
+ library_names_spec=
+ libname_spec='lib$name'
+@@ -10335,8 +10335,8 @@ darwin* | rhapsody*)
+   shlibpath_var=DYLD_LIBRARY_PATH
+   shrext_cmds='`test .$module = .yes && echo .so || echo .dylib`'
+ 
+-  sys_lib_search_path_spec="$sys_lib_search_path_spec /usr/local/lib"
+-  sys_lib_dlsearch_path_spec='/usr/local/lib /lib /usr/lib'
++  sys_lib_search_path_spec="$sys_lib_search_path_spec /opt/local/lib"
++  sys_lib_dlsearch_path_spec='/opt/local/lib /lib /usr/lib'
+   ;;
+ 
+ dgux*)
 diff --git encodefilter/module/Makefile.in encodefilter/module/Makefile.in
 index cf36d81e..c1db40ea 100644
 --- encodefilter/module/Makefile.in
@@ -121,7 +222,7 @@ index cf36d81e..c1db40ea 100644
  JAJP_TABLE_OBJ = ef_ucs4_jisx0208.o ef_ucs4_jisx0212.o ef_ucs4_jisx0213.o
  KOKR_TABLE_OBJ = ef_ucs4_uhc.o ef_uhc_johab.o
 diff --git encodefilter/src/Makefile.in encodefilter/src/Makefile.in
-index 5a008beb..0619fa14 100644
+index 0ac981d0..43627cb5 100644
 --- encodefilter/src/Makefile.in
 +++ encodefilter/src/Makefile.in
 @@ -16,7 +16,7 @@ VPATH = $(top_srcdir)/src
@@ -286,19 +387,6 @@ index e57849d8..2aac2734 100644
  
  LIBS = $(LIBS_LOCAL) @LPOBL@ @LMEF@ @WNN_LIBS@
  
-diff --git java/Makefile.in java/Makefile.in
-index dd7bcb04..9dc024c4 100644
---- java/Makefile.in
-+++ java/Makefile.in
-@@ -67,7 +67,7 @@ $(TARGET_win32) : MLTermPty.h
- 	(cd ../vtemu;rm -f vt_term.o;CFLAGS_LOCAL=-DOPEN_PTY_SYNC make vt_term.o mlterm.o)
- 	$(CC) -Wl,--kill-at $(CFLAGS) -shared -o MLTermPty.dll \
- 	$(top_srcdir)/java/MLTermPty.c ../vtemu/.libs/*.o ../baselib/src/.libs/libpobl.dll.a \
--	../encodefilter/src/.libs/libmef.dll.a -L/usr/local/lib @SSH2_LIBS_FOR_PROG@
-+	../encodefilter/src/.libs/libmef.dll.a @SSH2_LIBS_FOR_PROG@
- 	(rm -f ../vtemu/vt_term.o)
- 
- $(TARGET) : $(CLASS) MLTermPty.h $(OBJ)
 diff --git libind/Makefile.in libind/Makefile.in
 index 0fe45912..e01aa42d 100644
 --- libind/Makefile.in
@@ -382,10 +470,10 @@ index ccf716a4..38884a6c 100644
  
  DESTDIR=
 diff --git tool/mlconfig/Makefile.in tool/mlconfig/Makefile.in
-index 7e49dbc8..fef85335 100644
+index 88749109..9417068c 100644
 --- tool/mlconfig/Makefile.in
 +++ tool/mlconfig/Makefile.in
-@@ -26,7 +26,6 @@ CFLAGS = $(CFLAGS_LOCAL) @GTK_CFLAGS_FOR_MLCONFIG@ @IMAGELIB_CFLAGS@ @DEB_CFLAGS
+@@ -26,7 +26,6 @@ CFLAGS = $(CFLAGS_LOCAL) @GTK_CFLAGS@ @IMAGELIB_CFLAGS@ @DEB_CFLAGS@ \
  	-I${top_srcdir}/xwindow -I${top_srcdir}/vtemu \
  	-I${top_builddir}/common -I${top_srcdir}/common \
  	-I${top_srcdir}/inputmethod \
@@ -436,19 +524,20 @@ index f79a9a4d..91f9db96 100644
  PROG = mlfc
  
 diff --git tool/mlimgloader/Makefile.in tool/mlimgloader/Makefile.in
-index 60bcc9b7..6d7da5d4 100644
+index e2896a81..3bb15561 100644
 --- tool/mlimgloader/Makefile.in
 +++ tool/mlimgloader/Makefile.in
-@@ -23,7 +23,7 @@ LPOBL = @LPOBL@
+@@ -22,8 +22,7 @@ OBJ = @MLIMGLOADER_LIB@.o
+ LPOBL = @LPOBL@
  LPOBL_DEB = -lpobl_deb
  
- CFLAGS1 = $(CFLAGS_LOCAL) @POBL_CFLAGS@ @DEB_CFLAGS@ @GUI_CFLAGS@ @CFLAGS@ @CPPFLAGS@ \
--	@X_CFLAGS_AUX@ -I/usr/local/include
-+	@X_CFLAGS_AUX@
+-CFLAGS1 = $(CFLAGS_LOCAL) @POBL_CFLAGS@ @DEB_CFLAGS@ @GUI_CFLAGS@ @CFLAGS@ @CPPFLAGS@ \
+-	-I/usr/local/include
++CFLAGS1 = $(CFLAGS_LOCAL) @POBL_CFLAGS@ @DEB_CFLAGS@ @GUI_CFLAGS@ @CFLAGS@ @CPPFLAGS@
  
- CFLAGS2_gdk-pixbuf = @GDK_PIXBUF_CFLAGS@ @X_CFLAGS@ @EMOJI_CFLAGS@
- CFLAGS2_libpng = @LIBPNG_CFLAGS@ @X_CFLAGS@ @EMOJI_CFLAGS@
-@@ -31,7 +31,7 @@ CFLAGS2_libpng = @LIBPNG_CFLAGS@ @X_CFLAGS@ @EMOJI_CFLAGS@
+ CFLAGS2_gdk-pixbuf = @GDK_PIXBUF_CFLAGS@ @X_CFLAGS@ @X_CFLAGS_AUX@ @EMOJI_CFLAGS@
+ CFLAGS2_libpng = @LIBPNG_CFLAGS@ @X_CFLAGS@ @X_CFLAGS_AUX@ @EMOJI_CFLAGS@
+@@ -31,7 +30,7 @@ CFLAGS2_libpng = @LIBPNG_CFLAGS@ @X_CFLAGS@ @X_CFLAGS_AUX@ @EMOJI_CFLAGS@
  CFLAGS = $(CFLAGS1) $(CFLAGS2_@MLIMGLOADER_LIB@) -DLIBEXECDIR=\"$(libexecdir)\" \
  	-DBINDIR=\"$(bindir)\"
  
@@ -503,7 +592,7 @@ index 674ca0f1..734a1a1d 100644
  PROG = servman
  
 diff --git uitoolkit/Makefile.in uitoolkit/Makefile.in
-index c8311d1a..faf8cf92 100644
+index b7b96de5..b335d1e6 100644
 --- uitoolkit/Makefile.in
 +++ uitoolkit/Makefile.in
 @@ -66,7 +66,7 @@ CFLAGS = $(CFLAGS_LOCAL) @POBL_CFLAGS@ @MEF_CFLAGS@ @DEB_CFLAGS@ @MATH_CFLAGS@ \
@@ -516,7 +605,7 @@ index c8311d1a..faf8cf92 100644
  LIBTOOL_CC = $(LIBTOOL) --mode=compile $(CC) $(CFLAGS)
  LIBTOOL_LINK = $(LIBTOOL) --mode=link $(CC) @LDFLAGS@
 diff --git uitoolkit/fb/ui_virtual_kbd.c uitoolkit/fb/ui_virtual_kbd.c
-index 34cf9116..e7216b44 100644
+index c89d8dc1..dc421212 100644
 --- uitoolkit/fb/ui_virtual_kbd.c
 +++ uitoolkit/fb/ui_virtual_kbd.c
 @@ -20,7 +20,7 @@ ui_window_t *ui_is_virtual_kbd_area(int y) { return NULL; }
@@ -591,7 +680,7 @@ index 754ddfe4..5ea902ee 100644
  #define IM_DIR LIBDIR "/mlterm/"
  #endif
 diff --git uitoolkit/ui_sb_view_factory.c uitoolkit/ui_sb_view_factory.c
-index a8af0cde..555e3889 100644
+index e3c5fe66..5746bb40 100644
 --- uitoolkit/ui_sb_view_factory.c
 +++ uitoolkit/ui_sb_view_factory.c
 @@ -13,13 +13,13 @@
@@ -715,7 +804,7 @@ index e9bd3535..67ebce93 100644
  #define MOSHLIB_DIR LIBDIR "/mlterm/"
  #endif
 diff --git vtemu/vt_pty_ssh.c vtemu/vt_pty_ssh.c
-index e14f1696..e83abc5e 100644
+index 24997115..c9bdd8b3 100644
 --- vtemu/vt_pty_ssh.c
 +++ vtemu/vt_pty_ssh.c
 @@ -21,7 +21,7 @@
@@ -754,5 +843,5 @@ index bf4e7ee9..87da3ac4 100644
  #define TRANSFERLIB_DIR LIBDIR "/mlterm/"
  #endif
 -- 
-2.24.3 (Apple Git-128)
+2.54.0
 
